FROM centos:7 
RUN yum install wget -y 

RUN wget -O /tec/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
RUN rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
RUN yum install java -y && yum install jenkins -y
RUN yum install git -y 
EXPOSE 8080
RUN echo -e "jenkins ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

CMD  java  -jar /usr/lib/jenkins/jenkins.war 