
apiVersion: v1
kind: Pod
metadata:
  name: mywebpod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: mypvc1
  containers:
    - name: mywebpod
      image: httpd
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/www/html"
          name: pv-storage


