apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebpod
  labels:
     app: web-app
spec:
  selector:
     matchLabels:
       app: web-app
  strategy:
     type: RollingUpdate
  template:
     metadata:
        labels:
          app: web-app
     spec:
        containers:
        - name: mywebpod
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html"
              name: pv-storage
        volumes:
           - name: pv-storage
             persistentVolumeClaim:
                claimName: mypvc1
  
     
  


